"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { MealCard } from "@/components/MealCard";
import { ProteinSelector } from "@/components/ProteinSelector";
import { useAppState } from "@/lib/app-state";
import { MEAL_LABELS, MEAL_TYPES } from "@/lib/constants";
import { getMealParticipationAvailability } from "@/lib/household";
import { getBucketMealCompletion } from "@/lib/meal-buckets";
import { getRecipeMap, getSafeRecipes } from "@/lib/meal-generator";
import type { MealCounts, MealType } from "@/types";

const defaults: MealCounts = { breakfast: 7, brunch: 0, lunch: 7, dinner: 7 };
const clamp = (value: number) => Math.min(50, Math.max(0, Math.trunc(value)));

function CountSetup({ onGenerate }: { onGenerate: (counts: MealCounts) => void }) {
  const { preferences, toggleProtein, toggleFavoriteProtein } = useAppState();
  const availability = useMemo(() => getMealParticipationAvailability(preferences.householdMembers), [preferences.householdMembers]);
  const [counts, setCounts] = useState<MealCounts>(() => ({ ...defaults }));
  useEffect(() => setCounts((current) => MEAL_TYPES.reduce((next, type) => ({ ...next, [type]: availability[type] ? current[type] : 0 }), {} as MealCounts)), [availability]);
  const total = MEAL_TYPES.reduce((sum, type) => sum + counts[type], 0);
  const change = (type: MealType, value: number) => setCounts((current) => ({ ...current, [type]: availability[type] ? clamp(value) : 0 }));
  return <main className="space-y-6 p-4 pb-12">
    <section className="rounded-[32px] bg-gradient-to-br from-teal-200 via-cyan-100 to-sky-100 p-6 text-slate-900 shadow-panel dark:from-slate-800 dark:via-teal-900 dark:to-cyan-900 dark:text-white"><div className="text-xs font-semibold uppercase tracking-[0.24em]">Meals</div><h1 className="mt-3 text-3xl font-bold">Build a meal plan</h1><p className="mt-3 text-sm">Choose how many meals you want in each bucket. Plans never expire.</p></section>
    <section className="rounded-[32px] border border-border bg-surface p-4"><h2 className="text-lg font-semibold text-text">Meal counts</h2><div className="mt-4 space-y-3">{MEAL_TYPES.map((type) => <div key={type} className="flex items-center justify-between rounded-3xl bg-canvas p-3"><div><b className="text-text">{MEAL_LABELS[type]}</b>{!availability[type] ? <p className="text-xs text-muted">Unavailable for this household</p> : null}</div><div className="flex items-center gap-2"><button type="button" aria-label={`Decrease ${MEAL_LABELS[type]} count`} disabled={!availability[type] || counts[type] === 0} onClick={() => change(type, counts[type] - 1)} className="rounded-full bg-surfaceAlt px-3 py-2 disabled:opacity-40">−</button><input aria-label={`${MEAL_LABELS[type]} count`} type="number" min="0" max="50" disabled={!availability[type]} value={counts[type]} onChange={(event) => change(type, Number(event.target.value))} className="w-14 rounded-xl border border-border bg-surface px-2 py-2 text-center" /><button type="button" aria-label={`Increase ${MEAL_LABELS[type]} count`} disabled={!availability[type] || counts[type] === 50} onClick={() => change(type, counts[type] + 1)} className="rounded-full bg-surfaceAlt px-3 py-2 disabled:opacity-40">+</button></div></div>)}</div></section>
    <section className="rounded-[32px] border border-border bg-surface p-4"><h2 className="text-lg font-semibold text-text">Proteins</h2><div className="mt-4"><ProteinSelector selected={preferences.selectedProteins} pinned={preferences.favoriteProteins} onToggle={toggleProtein} onPin={toggleFavoriteProtein} /></div></section>
    <button type="button" disabled={total === 0} onClick={() => onGenerate(counts)} className="w-full rounded-full bg-accent px-5 py-4 text-base font-bold text-white disabled:opacity-40">Generate {total} meal{total === 1 ? "" : "s"}</button>
  </main>;
}

export default function PlanPage() {
  const { preferences, mealPlan, customRecipes, hydrated, syncError, hasLoadedSharedState, regenerateRemaining, regenerateMeal, assignRecipeToMeal, toggleMealConsumed, toggleFavoriteRecipe, generatePlan, clearPlan, addCustomRecipe, saveCurrentPlan, planSavedSinceLastChange } = useAppState();
  const [setup, setSetup] = useState(false); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState<string | null>(null); const [pending, setPending] = useState<"regenerate" | "new" | null>(null); const [consumedOpen, setConsumedOpen] = useState(false);
  const continueRef = useRef<HTMLButtonElement>(null);
  const recipeMap = useMemo(() => getRecipeMap(customRecipes, preferences.mealProfileId), [customRecipes, preferences.mealProfileId]);
  const options = useMemo(() => { const safe = getSafeRecipes(customRecipes, preferences.excludedIngredients, preferences.mealProfileId); return MEAL_TYPES.reduce((result, type) => ({ ...result, [type]: safe.filter((recipe) => recipe.mealType.includes(type) || (type === "brunch" && recipe.mealType.some((candidate) => candidate === "breakfast" || candidate === "lunch"))) }), {} as Record<MealType, typeof safe>); }, [customRecipes, preferences.excludedIngredients, preferences.mealProfileId]);
  useEffect(() => { if (!pending) return; continueRef.current?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape" && !saving) setPending(null); }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [pending, saving]);
  if (!hydrated) return <main className="p-6 text-sm text-muted">Loading your plan...</main>;
  if (!hasLoadedSharedState && syncError) return <main className="p-6 text-sm text-muted">Couldn&apos;t load your saved plan. {syncError}</main>;
  if (!mealPlan || setup) return <CountSetup onGenerate={(counts) => { generatePlan(counts); setSetup(false); }} />;
  const completion = getBucketMealCompletion(mealPlan);
  const replace = (action: "regenerate" | "new") => { if (action === "regenerate") regenerateRemaining(); else { clearPlan(); setSetup(true); } };
  const act = (action: "regenerate" | "new") => { if (!planSavedSinceLastChange) return setPending(action); replace(action); };
  const save = async () => { if (saving) return false; setSaving(true); setSaveError(null); const archive = await saveCurrentPlan(); setSaving(false); if (!archive) { setSaveError("Couldn’t save this plan. Please retry before continuing."); return false; } return true; };
  const unavailable = (type: MealType, meal: { id: string; unsafeRecipeId?: string; unsafeExcludedIngredients?: string[] }) => { const recipe = meal.unsafeRecipeId ? recipeMap.get(meal.unsafeRecipeId) : undefined; return <div className="rounded-3xl border border-amber-300 bg-amber-50 p-4 text-sm"><b>{meal.unsafeRecipeId ? recipe?.name ?? "Unavailable recipe" : "Recipe unavailable"}</b>{meal.unsafeRecipeId ? <p className="mt-1">{meal.unsafeExcludedIngredients?.length ? `Contains excluded ingredient${meal.unsafeExcludedIngredients.length === 1 ? "" : "s"}: ${meal.unsafeExcludedIngredients.join(", ")}. ` : "This recipe is blocked by your allergen exclusions. "}It is excluded from groceries and generation.</p> : <p className="mt-1">This recipe is no longer available.</p>}<button type="button" onClick={() => regenerateMeal(meal.id)} className="mt-2 font-semibold underline">Replace with safe meal</button></div>; };
  return <main className="space-y-6 p-4 pb-12">
    <section className="rounded-[32px] bg-gradient-to-br from-teal-200 via-cyan-100 to-sky-100 p-6 text-slate-900 shadow-panel dark:from-slate-800 dark:via-teal-900 dark:to-cyan-900 dark:text-white"><div className="text-xs font-semibold uppercase tracking-[0.24em]">Meals</div><h1 className="mt-3 text-3xl font-bold">Meal plan</h1><p className="mt-3 text-sm">{completion.remaining} meals left · {preferences.selectedProteins.length} protein groups.</p><div className="mt-3 flex flex-wrap gap-2 text-xs">{MEAL_TYPES.map((type) => { const total = mealPlan.buckets[type].length; const remaining = mealPlan.buckets[type].filter((meal) => !meal.consumed).length; return total ? <span key={type} className="rounded-full bg-white/50 px-3 py-1">{MEAL_LABELS[type]} {remaining}/{total}</span> : null; })}</div><div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={saving} onClick={() => { void save(); }} className="rounded-full bg-white/75 px-5 py-3 text-sm font-semibold text-slate-900 disabled:opacity-50">{saving ? "Saving…" : "Save this plan"}</button><button type="button" onClick={() => act("regenerate")} className="rounded-full bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Regenerate remaining</button><button type="button" onClick={() => act("new")} className="rounded-full border border-slate-900/20 px-5 py-3 text-sm font-semibold">New plan</button></div></section>
    {saveError ? <section role="alert" className="rounded-3xl border border-rose-400 bg-rose-50 p-4 text-sm text-rose-800">{saveError}</section> : null}{syncError ? <section className="rounded-3xl border border-amber-400 bg-amber-50 p-4 text-sm">{syncError}</section> : null}
    {completion.remaining === 0 ? <section className="rounded-[32px] border border-accent bg-accentSoft p-5"><h2 className="text-xl font-semibold text-text">Plan complete — {completion.completed} meals enjoyed</h2><button type="button" onClick={() => act("new")} className="mt-4 rounded-full bg-accent px-5 py-3 text-sm font-semibold text-white">Start next plan</button></section> : null}
    {MEAL_TYPES.map((type) => { const active = mealPlan.buckets[type].filter((meal) => !meal.consumed); if (!active.length) return null; return <section key={type} className="space-y-3"><h2 className="px-1 text-xl font-semibold text-text">{MEAL_LABELS[type]}</h2>{active.map((meal) => { const recipe = meal.recipeId ? recipeMap.get(meal.recipeId) : undefined; return recipe ? <MealCard key={meal.id} mealType={type} recipe={recipe} favorite={preferences.favoriteRecipeIds.includes(recipe.id)} favoriteRecipeIds={preferences.favoriteRecipeIds} consumed={false} recipeOptions={options[type]} onAssignRecipe={(recipeId) => assignRecipeToMeal(meal.id, recipeId)} onRegenerate={(protein) => regenerateMeal(meal.id, protein)} onToggleConsumed={() => toggleMealConsumed(meal.id)} onToggleFavorite={() => toggleFavoriteRecipe(recipe.id)} onCreateCustomMeal={async (recipe) => { await addCustomRecipe(recipe, { assignToMealId: meal.id }); }} /> : <div key={meal.id}>{unavailable(type, meal)}</div>; })}</section>; })}
    {completion.completed ? <section className="rounded-[32px] border border-border bg-surface p-4"><button type="button" onClick={() => setConsumedOpen((value) => !value)} className="text-lg font-semibold text-text">Consumed ({completion.completed}) {consumedOpen ? "⌃" : "⌄"}</button>{consumedOpen ? <div className="mt-3 space-y-3">{MEAL_TYPES.flatMap((type) => mealPlan.buckets[type].filter((meal) => meal.consumed).map((meal) => { const recipe = meal.recipeId ? recipeMap.get(meal.recipeId) : undefined; return recipe ? <MealCard key={meal.id} mealType={type} recipe={recipe} favorite={preferences.favoriteRecipeIds.includes(recipe.id)} favoriteRecipeIds={preferences.favoriteRecipeIds} consumed recipeOptions={[]} onAssignRecipe={async () => false} onRegenerate={() => undefined} onToggleConsumed={() => toggleMealConsumed(meal.id)} onToggleFavorite={() => toggleFavoriteRecipe(recipe.id)} onCreateCustomMeal={() => undefined} /> : <div key={meal.id} className="flex items-center justify-between rounded-2xl bg-canvas p-3 text-sm"><span>{MEAL_LABELS[type]} · {meal.unsafeRecipeId ? `${recipeMap.get(meal.unsafeRecipeId)?.name ?? "Unavailable recipe"}${meal.unsafeExcludedIngredients?.length ? ` (excluded: ${meal.unsafeExcludedIngredients.join(", ")})` : ""}` : "Recipe unavailable"}</span><button type="button" onClick={() => toggleMealConsumed(meal.id)} className="font-semibold text-accent">Undo</button></div>; }))}</div> : null}</section> : null}
    {pending ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section role="dialog" aria-modal="true" aria-labelledby="save-changes-title" className="max-w-sm rounded-3xl bg-surface p-5 shadow-panel"><h2 id="save-changes-title" className="text-lg font-semibold">Save changes first?</h2><p className="mt-2 text-sm text-muted">Your current plan has unsaved changes. Replacing it is irreversible.</p>{saveError ? <p role="alert" className="mt-2 text-sm text-rose-700">{saveError}</p> : null}<div className="mt-4 flex gap-2"><button ref={continueRef} type="button" disabled={saving} onClick={async () => { if (await save()) { const action = pending; setPending(null); replace(action); } }} className="rounded-full bg-accent px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save then continue"}</button><button type="button" disabled={saving} onClick={() => { const action = pending; setPending(null); replace(action); }} className="rounded-full bg-surfaceAlt px-4 py-2 text-sm disabled:opacity-50">Replace anyway</button><button type="button" disabled={saving} onClick={() => setPending(null)} className="text-sm underline disabled:opacity-50">Cancel</button></div></section></div> : null}
  </main>;
}
