"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useMemo, useState } from "react";
import { RecipeDetail } from "@/components/RecipeDetail";
import { CATEGORY_LABELS, MEAL_LABELS } from "@/lib/constants";
import { useAppState } from "@/lib/app-state";
import { formatDay, formatSavedAt } from "@/lib/date";
import { getAllRecipes, getRecipeMap } from "@/lib/meal-generator";
import { SAVED_WEEKS_PAGE_SIZE, searchRecipeArchive } from "@/lib/saved-archive";
import { getArchivedMealCount, getArchivedMealSlot, getEnabledArchivedMealTypes } from "@/lib/saved-week";
import type { GroceryItem, MealType, SavedBucketPlan, SavedWeek } from "@/types";

const isBucket = (record: SavedWeek | SavedBucketPlan): record is SavedBucketPlan => "kind" in record && record.kind === "bucket-plan";
function ArchiveMeal({ mealType, recipeId }: { mealType: MealType; recipeId?: string }) { const { preferences, customRecipes } = useAppState(); const recipe = getRecipeMap(customRecipes, preferences.mealProfileId).get(recipeId ?? ""); const [open, setOpen] = useState(false); return <article className="rounded-3xl border border-border bg-surface p-4"><button type="button" onClick={() => setOpen((value) => !value)} className="w-full text-left"><div className="text-xs font-semibold uppercase tracking-widest text-muted">{MEAL_LABELS[mealType]}</div><h3 className="mt-2 text-lg font-semibold text-text">{recipe?.name ?? "Recipe unavailable"}</h3><p className="mt-1 text-sm text-muted">{recipe?.description ?? "This recipe is no longer available."}</p></button>{open && recipe ? <RecipeDetail recipe={recipe} mealType={mealType} /> : null}</article>; }
function Groceries({ items }: { items: GroceryItem[] }) { const { sectionOrder } = useAppState(); return <>{sectionOrder.map((category) => { const group = items.filter((item) => item.category === category); return group.length ? <section key={category} className="rounded-3xl border border-border bg-surface p-4"><h2 className="font-semibold">{CATEGORY_LABELS[category]}</h2><div className="mt-3 space-y-2">{group.map((item) => <div key={item.key} className="flex justify-between rounded-2xl bg-canvas px-3 py-2 text-sm"><span>{item.name}</span><span>{item.quantity} {item.unit}</span></div>)}</div></section> : null; })}</>; }
function SavedContent() {
 const { hydrated, customRecipes, preferences, savedWeeks, deleteSavedPlan, toggleFavoriteRecipe } = useAppState(); const router = useRouter(); const params = useSearchParams(); const selected = params.get("id"); const record = selected ? savedWeeks.find((item) => item.id === selected) : undefined; const [visible, setVisible] = useState(SAVED_WEEKS_PAGE_SIZE); const [query, setQuery] = useState(""); const recipes = useMemo(() => searchRecipeArchive(getAllRecipes(customRecipes, preferences.mealProfileId), query), [customRecipes, preferences.mealProfileId, query]); const plans = savedWeeks.slice(0, Math.max(0, visible));
 if (!hydrated) return <main className="p-6 text-sm text-muted">Loading saved plans...</main>;
 if (record) { const allGroceries: GroceryItem[] = [...record.groceryList, ...record.customGroceryItems.map((item) => ({ ...item, key: item.id, isStaple: false }))]; return <main className="space-y-6 p-4 pb-12"><section className="rounded-[32px] bg-gradient-to-br from-teal-200 via-cyan-100 to-sky-100 p-6"><div className="text-xs font-semibold uppercase tracking-widest">Saved plan</div><h1 className="mt-3 text-3xl font-bold">{record.label}</h1><p className="mt-2 text-sm">Saved {formatSavedAt(record.savedAt)} · {getArchivedMealCount(record)} meals</p><div className="mt-4 flex gap-3"><button type="button" onClick={() => router.push("/saved")} className="rounded-full bg-slate-900 px-4 py-2 text-sm text-white">Back to plans</button><button type="button" onClick={() => { deleteSavedPlan(record.id); router.push("/saved"); }} className="rounded-full border border-slate-900 px-4 py-2 text-sm">Delete plan</button></div></section>{isBucket(record) ? <>{["breakfast", "brunch", "lunch", "dinner"].map((type) => record.mealPlan.buckets[type as MealType].length ? <section key={type} className="space-y-3"><h2 className="text-xl font-semibold">{MEAL_LABELS[type as MealType]}</h2>{record.mealPlan.buckets[type as MealType].map((meal) => <ArchiveMeal key={meal.id} mealType={type as MealType} recipeId={meal.recipeId ?? meal.unsafeRecipeId} />)}</section> : null)}</> : <>{record.mealPlan.days.map((day) => { const enabled = getEnabledArchivedMealTypes(day); return enabled.length ? <section key={day.date} className="space-y-3"><div><h2 className="text-xl font-semibold">{formatDay(day.date).weekday}</h2><p className="text-sm text-muted">{formatDay(day.date).label}</p></div>{enabled.map((type) => <ArchiveMeal key={type} mealType={type} recipeId={getArchivedMealSlot(day, type).recipeId} />)}</section> : null; })}</>}<Groceries items={allGroceries} /></main>; }
 return <main className="space-y-6 p-4 pb-12"><section className="rounded-[32px] bg-gradient-to-br from-teal-200 via-cyan-100 to-sky-100 p-6"><div className="text-xs font-semibold uppercase tracking-widest">Plans</div><h1 className="mt-3 text-3xl font-bold">Saved plans</h1><p className="mt-2 text-sm">Finalized meal plans stay here as a shared archive.</p></section>{plans.length ? <section className="space-y-3">{plans.map((plan) => <Link key={plan.id} href={`/saved?id=${plan.id}`} className="block rounded-3xl border border-border bg-surface p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-semibold">{plan.label}</h2><p className="mt-1 text-sm text-muted">Saved {formatSavedAt(plan.savedAt)}</p></div><span className="rounded-full bg-surfaceAlt px-3 py-2 text-xs">{getArchivedMealCount(plan)} meals</span></div></Link>)}{savedWeeks.length > plans.length ? <button type="button" onClick={() => setVisible((value) => value + SAVED_WEEKS_PAGE_SIZE)} className="w-full rounded-3xl border border-dashed border-border p-4 text-sm">Show more plans</button> : null}</section> : <section className="rounded-3xl border border-dashed border-border p-6 text-sm text-muted">Save a plan from the Plan page to build your archive.</section>}<section className="rounded-3xl border border-border bg-surface p-5"><h2 className="text-2xl font-semibold">Recipe archive</h2><p className="mt-1 text-sm text-muted">Search the full Meals recipe library, including your custom recipes.</p><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search recipes, cuisines, proteins, or ingredients" className="mt-4 w-full rounded-2xl border border-border bg-canvas px-4 py-3 text-sm"/><div className="mt-4 space-y-3">{recipes.map((recipe) => <article key={recipe.id} className="rounded-3xl border border-border p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{recipe.name}</h3><p className="mt-1 text-sm text-muted">{recipe.description}</p></div><button type="button" onClick={() => toggleFavoriteRecipe(recipe.id)} className="rounded-full bg-surfaceAlt px-3 py-2">{preferences.favoriteRecipeIds.includes(recipe.id) ? "★" : "☆"}</button></div><RecipeDetail recipe={recipe} mealType={recipe.mealType[0] ?? "dinner"} /></article>)}</div></section></main>;
}
export default function SavedPage() { return <Suspense fallback={<main className="p-6 text-sm text-muted">Loading saved plans...</main>}><SavedContent /></Suspense>; }
